# Generated by Django 5.1.1 on 2025-09-20 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_zona', models.CharField(choices=[('segura', 'Segura'), ('publica', 'Pública')], default='publica', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='app.usuariosistema')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='app.zona')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ingresos/')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.registroingreso')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_habilitado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app.usuariosistema')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app.zona')),
            ],
            options={
                'unique_together': {('usuario', 'zona')},
            },
        ),
    ]
