# Generated by Django 5.1.1 on 2025-10-13 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('licencia', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_gps', models.CharField(max_length=50, unique=True)),
                ('coordenada_lat', models.FloatField(blank=True, null=True)),
                ('coordenada_long', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.gps')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='app.conductor')),
                ('gps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo', to='app.gps')),
            ],
        ),
    ]
